server:
  port: 8280

spring:
  application:
    name: CouponFury-engine
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  rabbitmq:
    addresses: 120.26.236.122
    port: 5672
    username: springleaf
    password: 123123
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    topic:
      user-coupon-redeem: user.coupon.redeem
      coupon-remind-delay: coupon.remind.delay

mybatis:
  mapper-locations: classpath:/mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true


springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.springleaf.couponfury

knife4j:
  enable: true
  setting:
    language: zh_cn