server:
  port: 8180

spring:
  application:
    name: CouponFury-merchant-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  rabbitmq:
    addresses: 120.26.236.122
    port: 5672
    username: springleaf
    password: 123123
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个


mybatis:
  mapper-locations: classpath:/mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true

xxl-job:
  # 是否开启xxl-job
  enabled: false
  access-token: default_token
  admin:
    addresses: http://127.0.0.1:7080/xxl-job-admin
  executor:
    application-name: coupon-fury-merchant-admin
    ip: 127.0.0.1
    log-retention-days: 30
    port: 19999

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.springleaf.couponfury

knife4j:
  enable: true
  setting:
    language: zh_cn