# 数据源集合
dataSources:
  # 自定义数据源名称，可以是 ds_0 也可以叫 datasource_0 都可以
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/coupon_fury_0?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/coupon_fury_1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

rules:
  - !SHARDING
    tables: # 需要分片的数据库表集合
      t_coupon_settlement: # 结算表
        # 真实存在数据库中的物理表
        actualDataNodes: ds_${0..1}.t_coupon_settlement_${0..7}
        databaseStrategy: # 分库策略
          standard: # 单分片键分库
            shardingColumn: user_id # 分片键
            shardingAlgorithmName: coupon_settlement_database_mod # 库分片算法名称，对应 rules[0].shardingAlgorithms
        tableStrategy: # 分表策略
          standard: # 单分片键分表
            shardingColumn: user_id # 分片键
            shardingAlgorithmName: coupon_settlement_table_mod # 表分片算法名称，对应 rules[0].shardingAlgorithms

    shardingAlgorithms: # 分片算法定义集合
      coupon_settlement_database_mod: # 结算分库算法定义
        type: CLASS_BASED # 根据自定义库分片算法类进行分片
        props: # 分片相关属性
          # 自定义库分片算法Class
          algorithmClassName: com.couponfury.springleaf.settlement.dao.sharding.DBHashModShardingAlgorithm
          sharding-count: 16 # 分片总数量
          strategy: standard # 分片类型，单字段分片
      coupon_settlement_table_mod: # 结算分表算法定义
        type: CLASS_BASED # 根据自定义库分片算法类进行分片
        props: # 分片相关属性
          # 自定义表分片算法Class
          algorithmClassName: com.couponfury.springleaf.settlement.dao.sharding.TableHashModShardingAlgorithm
          strategy: standard # 分片类型，单字段分片

props:
  # 配置 ShardingSphere 默认打印 SQL 执行语句
  sql-show: true