server:
  port: 8085

spring:
  application:
    name: CouponFury-distribution
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    data:
      redis:
        host: 127.0.0.1
        port: 6379
        database: 0
  rabbitmq:
    addresses: 120.26.236.122
    port: 5672
    username: springleaf
    password: 123123
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    topic:
      coupon-task-execute: coupon.task.execute
      coupon-execute-distribution: coupon.execute.distribution


mybatis:
  mapper-locations: classpath:/mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  pageSizeZero: true